version: "3"

volumes:
  gitea:
    driver: "local"
  postgres:
    driver: "local"
  runner:
    driver: "local"

networks:
  gitea:
    external: false

services:
  gitea:
    container_name: "gitea"
    image: "gitea/gitea:nightly"
    restart: "always"
    environment:
      - "USER=git"
      - "USER_UID=1000"
      - "USER_GID=1000"
      - "GITEA__database__DB_TYPE=postgres"
      - "GITEA__database__HOST=postgres:5432"
      - "GITEA__database__NAME=gitea"
      - "GITEA__database__USER=gitea"
      - "GITEA__database__PASSWD=gitea"
      - "GITEA__actions__ENABLED=true"
    volumes:
      - "gitea:/data"
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - "22:22"
      - "127.0.0.1:3000:3000"
    networks:
      - "gitea"
    depends_on:
      - "postgres"

  postgres:
    container_name: "postgres"
    image: "postgres:latest"
    restart: "always"
    environment:
      - "POSTGRES_USER=gitea"
      - "POSTGRES_PASSWORD=gitea"
      - "POSTGRES_DB=gitea"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    networks:
      - "gitea"

  caddy:
    container_name: "caddy"
    image: "slothcroissant/caddy-cloudflaredns:latest"
    restart: "always"
    volumes:
      - "./caddy/Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - "gitea"
    depends_on:
      - "gitea"

  runner:
    container_name: "runner"
    image: "gitea/act_runner:nightly"
    restart: "always"
    environment:
      CONFIG_FILE: "/config.yml"
      GITEA_INSTANCE_URL: "http://127.0.0.1:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "<runner_registration_token>"
      GITEA_RUNNER_NAME: "PlayUnlimited"
      GITEA_RUNNER_LABELS: ""
    volumes:
      - "./runner/config.yml:/config.yml"
      - "runner:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"
    network_mode: "host"
    depends_on:
      - "gitea"